Recomendo.Website/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using Recomendo.Website.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Recomendo.Website.Controllers
{
    public class CategoryController : Controller
    {
        private readonly IRepository repository;

        public CategoryController(IRepository repository)
        {
            this.repository = repository;
        }

        public IActionResult Index()
        {
            return View(repository.Categories);
        }

        public IActionResult Edit(int id)
        {
            var category = repository.Categories.FirstOrDefault(x => x.Id == id);
            return View(category);
        }

        [HttpPost]
        public IActionResult Edit(Category category)
        {
            if (ModelState.IsValid)
            {
                repository.Update(category);
                return RedirectToAction(nameof(Index));
            }

            return View(category);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Category category)
        {
            if (ModelState.IsValid)
            {
                repository.Add(category);
                return RedirectToAction(nameof(Index));
            }

            return View(category);
        }

        public IActionResult Delete(int id)
        {
            var category = repository.Categories.FirstOrDefault(x => x.Id == id);
            return View(category);
        }

        [HttpPost]
        public IActionResult Delete(Category category)
        {
            repository.Delete(category);
            return RedirectToAction(nameof(Index));
        }
    }
}

Recomendo.Website/Controllers/MovieController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Recomendo.Website.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace Recomendo.Website.Controllers
{
    public class MovieController : Controller
    {
        private readonly IRepository repository;
        private readonly IWebHostEnvironment webHostEnvironment;

        public MovieController(IRepository repository, IWebHostEnvironment webHostEnvironment)
        {
            this.repository = repository;
            this.webHostEnvironment = webHostEnvironment;
        }

        public IActionResult Index()
        {
            return View(repository.Movies);
        }

        public IActionResult Details(int id)
        {
            var movie = repository.Movies.FirstOrDefault(x => x.Id == id);
            return View(movie);
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            var movie = repository.Movies.FirstOrDefault(x => x.Id == id);
            return View(movie);
        }

        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteConfirmed(int id)
        {
            var movie = repository.Movies.FirstOrDefault(x => x.Id == id);
            repository.Delete(movie);

            return RedirectToAction(nameof(Index));
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Movie movie)
        {
            var imagePath = @"\images\movies\";
            var hasAttachment = HttpContext.Request.Form.Files.Count > 0;

            if (!hasAttachment)
                ModelState.AddModelError(nameof(Movie.Image), "A Capa ou Poster do Filme é Obrigatório");

            if (ModelState.IsValid)
            {
                if (hasAttachment)
                {
                    var files = HttpContext.Request.Form.Files;
                    string webRootPath = webHostEnvironment.WebRootPath;
                    string upload = webRootPath + imagePath;
                    string fileName = Guid.NewGuid().ToString();
                    string extension = Path.GetExtension(files[0].FileName);

                    using (var fileStream = new FileStream(Path.Combine(upload, fileName + extension), FileMode.Create))
                    {
                        files[0].CopyTo(fileStream);
                    }
                    movie.Image = fileName + extension;
                }


                repository.Add(movie);
                return RedirectToAction(nameof(Index));
            }
            return View(movie);
        }

        public IActionResult Edit(int id)
        {
            var movie = repository.Movies.FirstOrDefault(x => x.Id == id);
            return View(movie);
        }

        [HttpPost]
        public IActionResult Edit(Movie movie)
        {
            var imagePath = @"\images\movies\";
            var hasAttachment = HttpContext.Request.Form.Files.Count > 0;

            if (hasAttachment)
            {
                var files = HttpContext.Request.Form.Files;
                string webRootPath = webHostEnvironment.WebRootPath;
                string upload = webRootPath + imagePath;
                string fileName = Guid.NewGuid().ToString();
                string extension = Path.GetExtension(files[0].FileName);

                using (var fileStream = new FileStream(Path.Combine(upload, fileName + extension), FileMode.Create))
                {
                    files[0].CopyTo(fileStream);
                }
                movie.Image = fileName + extension;
            }

            repository.Update(movie);
            return RedirectToAction(nameof(Index));
        }
    }
}

Recomendo.Website/Views/Shared/_Layout.cshtml
@{
    @using Recomendo.Website.Controllers;
    var rv = ViewContext.RouteData.Values;
    var currentController = $"{rv["controller"]}";
}
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/font-awesome/css/all.css" />
    <link rel="stylesheet" href="~/site.css" />
    <link href="~/summernote/summernote.min.css" rel="stylesheet">
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
        <a class="navbar-brand" href="#">Recomendo - Avaliações de Filmes</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample03" aria-controls="navbarsExample03" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarsExample03">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item" active-target-controller-name="@nameof(HomeController)" active-current-controller-name="@currentController">
                    <a asp-controller="Home" asp-action="Index" class="nav-link">Home</a>
                </li>
                <li class="nav-item" active-target-controller-name="@nameof(CategoryController)" active-current-controller-name="@currentController">
                    <a asp-controller="Category" asp-action="Index" class="nav-link">Categorias</a>
                </li>
                <li class="nav-item" active-target-controller-name="@nameof(MovieController)" active-current-controller-name="@currentController">
                    <a asp-controller="Movie" asp-action="Index" class="nav-link">Filmes</a>
                </li>
                <li class="nav-item dropdown" active-target-controller-name="Drop" active-current-controller-name="@currentController">
                    <a class="nav-link dropdown-toggle" href="http://example.com" id="dropdown03" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Dropdown</a>
                    <div class="dropdown-menu" aria-labelledby="dropdown03">
                        <a class="dropdown-item" href="#">Action</a>
                        <a class="dropdown-item" href="#">Another action</a>
                        <a class="dropdown-item" href="#">Something else here</a>
                    </div>
                </li>
            </ul>
            <form class="form-inline my-2 my-md-0">
                <input class="form-control" type="text" placeholder="Search" control-id="ControlID-2">
            </form>
        </div>
    </nav>
    <div>
        @RenderBody()
    </div>
    <script src="~/popper.js/umd/popper.js"></script>
    <script src="~/jquery/jquery.min.js"></script>
    <script src="~/summernote/summernote.min.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>